prod_dict = {
    'accumulo': ['cdp private cloud', 'cdp public cloud'],
    'altus': ['altus'],
    'ambari': ['hdp', 'hdf'],
    'apache hive jdbc connector': ['cdp private cloud', 'cdp public cloud', 'hdp', 'cdh'],
    'apache kafka': ['cdp private cloud', 'cdp public cloud', 'hdp', 'cdh', 'hdf', 'csa', 'smm', 'sam', 'cdf', 'cfm'],
    'apache kudu': ['cdp private cloud', 'cdp public cloud', 'cdh'],
    'apache spark': ['cdp private cloud', 'cdp public cloud', 'hdp', 'cdh'],
    'arcadia data': [],
    'best practices': [],
    'bigsql': [],
    'cazena': ['cazena'],
    'ccp': ['ccp'],
    'cdf-datahub': ['cdf'],
    'cdh': ['cdh'],
    'cdp': ['cdp private cloud', 'cdp public cloud'],
    'cdp 7.1.7': ['cdp private cloud', 'cdp public cloud'],
    'cdp data center': ['cdp private cloud'],
    'cdp one': ['cdp one'],
    'cdp-one': ['cdp one'],
    'cdp private cloud': ['cdp private cloud'],
    'cdp-private-cloud': ['cdp private cloud'],
    'cdp private cloud base': ['cdp private cloud'],
    'cdp-private-cloud-base': ['cdp private cloud'],
    'cdp private cloud data services': ['cdp private cloud'],
    'cdp-private-cloud-data-services': ['cdp private cloud'],
    'cdp private cloud upgrade': ['cdp private cloud'],
    'cdp-private-cloud-upgrade': ['cdp private cloud'],
    'cdp public cloud': ['cdp public cloud'],
    'cdp-public-cloud': ['cdp public cloud'],
    'cdp-public-cloud-patterns': ['cdp public cloud'],
    'cdp-reference-architectures': ['cdp public cloud'],
    'cdsw': ['cdsw'],
    'cem': ['cem'],
    'cfm': ['cfm'],
    'cloudbreak': ['cloudbreak'],
    'cloudera cdh enterprise': ['cdh'],
    'cloudera cybersecurity platform': ['ccp'],
    'cloudera data catalog': ['cdp private cloud', 'cdp public cloud'],
    'cloudera data engineering': ['cde'],
    'cloudera dataflow': ['cdf'],
    'cloudera dataflow (cdf)': ['cdf'],
    'cloudera dataflow for data hub': ['cdf'],
    'cloudera data hub': ['cdh'],
    'cloudera data hub 5.x': ['cdh'],
    'cloudera data hub 6.x': ['cdh'],
    'cloudera data platform (cdp)': ['cdp private cloud', 'cdp public cloud'],
    'cloudera data science and engineering': ['cde'],
    'cloudera data science workbench': ['cdsw'],
    'cloudera data visualization': ['cdv'],
    'cloudera data warehouse': ['cdw'],
    'cloudera director': ['altus'],
    'cloudera edge management': ['cem'],
    'cloudera enterprise data hub': ['cdh'],
    'cloudera essentials': [],
    'cloudera flow management': ['cfm'],
    'cloudera guru how to': [],
    'cloudera machine learning': ['cml'],
    'cloudera management console': ['cdp private cloud', 'cdp public cloud', 'cdh'],
    'cloudera manager': ['cdp private cloud', 'cdp public cloud', 'cdh'],
    'cloudera-manager': ['cdp private cloud', 'cdp public cloud', 'cdh'],
    'cloudera-manager-ibm': ['cdp private cloud', 'cdp public cloud', 'cdh'],
    'cloudera navigator optimizer': ['cdh'],
    'cloudera observability': ['observability'],
    'cloudera operational database': ['cod'],
    'cloudera operational db': ['cod'],
    'cloudera reference architecture': [],
    'cloudera replication manager': ['replication manager'],
    'cloudera runtime': ['cdp private cloud', 'cdp public cloud'],
    'cloudera security bulletins': [],
    'cloudera streaming analytics': ['csa'],
    'cloudera streaming analytics (csa)': ['csa'],
    'cloudera stream processing': ['csa', 'cdf'],
    'cloudera workload xm (wxm)': ['wxm'],
    'csa': ['csa'],
    'csp': ['csp'],
    'csp-ce': ['csp'],
    'cybersecurity': ['ccp'],
    'data analytics studio': ['das'],
    'data-catalog': ['cdp private cloud', 'cdp public cloud'],
    'datacoral': ['datacoral'],
    'data-engineering': ['cde'],
    'dataflow': ['cdf'],
    'data-hub': ['cdh'],
    'data lifecycle manager': ['dlm'],
    'dataplane': ['cdp public cloud'],
    'data platform': ['cdp private cloud', 'cdp public cloud'],
    'data-science-workbench': ['cdsw'],
    'data steward studio': [''],
    'data-warehouse': ['cdw'],
    'data warehouse runtime': ['cdw'],
    'director': ['altus'],
    'enterprise': ['cdh'], # TODO we need to check this
    'hcp': ['hcp'],
    'hcp1': ['hcp'],
    'hdf': ['hdf'],
    'hdf3': ['hdf'],
    'hdp': ['hdp'],
    'hdp1': ['hdp'],
    'hdp2': ['hdp'],
    'hdp 2.x': ['hdp'],
    'hdp3': ['hdp'],
    'hdp 3.x': ['hdp'],
    'hdpdocuments': ['hdp'],
    'hdpforcloud': ['hdp'],
    'hdps': ['hdp'],
    'hive-jdbc': ['cdp private cloud', 'cdp public cloud', 'hdp', 'cdh'],
    'hive-odbc': ['cdp private cloud', 'cdp public cloud', 'hdp', 'cdh'],
    'hortonworks dataplane': ['dps'],
    'hortonworks data platform (hdp)': ['hdp'],
    'hue': ['cdp private cloud', 'cdp public cloud', 'cdh'],
    'ibm big sql': [],
    'impala-jdbc': ['cdp private cloud', 'cdp public cloud', 'cdh'],
    'impala-odbc': ['cdp private cloud', 'cdp public cloud', 'cdh'],
    'kafka': ['cdp private cloud', 'cdp public cloud', 'hdp', 'cdh', 'hdf', 'csa', 'smm', 'sam', 'cdf', 'cfm'],
    'kudu': ['cdp private cloud', 'cdp public cloud', 'cdh'],
    'machine-learning': ['cml'],
    'management-console': ['cdp private cloud', 'cdp public cloud', 'cdh'],
    'manager': ['cdp private cloud', 'cdp public cloud', 'cdh'],
    'observability': ['observability'],
    'operational-database': ['cod'],
    'posts': [],
    'replication-manager': ['replication manager'],
    'runtime': ['cdp private cloud', 'cdp public cloud'],
    'smartsense': ['hdp'],
    'spark2': ['cdp private cloud', 'cdp public cloud', 'hdp', 'cdh'],
    'spark-odbc': ['cdh'],
    'streams replication manager': ['srm'],
    'wxm': ['wxm'],
    'yarn': ['cdp private cloud', 'cdp public cloud', 'hdp', 'cdh']
}

def standardize_name(name):
    ret = []
    if not type(name) is list:
        name = name.split(',')
    for p_name in name:
        n = p_name.strip().lower()
        prods = prod_dict.get(n)
        if prods and len(prods)>0:
            ret.extend(prods)
    return list(set(ret))